"use client";

import { useEffect, useState } from "react";
import Link from "next/link";
import { useParams } from "next/navigation";
import { ArrowLeft, Loader2, Pencil, Save } from "lucide-react";

type Member = Record<string, unknown> & { id: string; name: string; role: string; phone: string; territory: string; category: string; status: string; skills: string[]; email?: string; dob?: string; address?: string; department?: string; joiningDate?: string; employmentType?: string; reportingManager?: string; monthlySalary?: number; bankAccountHolder?: string; bankName?: string; bankAccountNumber?: string; bankIFSC?: string; bankBranch?: string; bankAccountType?: string; upiId?: string; emailVerifiedAt?: string | null; employeeAccessEnabled?: boolean };
const input = "mt-1 w-full rounded-lg border border-emerald-200 bg-white px-2.5 py-1.5 text-sm font-semibold text-slate-800 outline-none focus:border-emerald-600";
const label = "text-xs font-bold uppercase tracking-wide text-slate-400";

export default function EmployeeProfilePage() {
  const { memberId } = useParams<{ memberId: string }>();
  const [members, setMembers] = useState<Member[]>([]), [member, setMember] = useState<Member | null>(null), [editing, setEditing] = useState(false), [saving, setSaving] = useState(false), [error, setError] = useState(""), [verificationCode, setVerificationCode] = useState(""), [verificationMessage, setVerificationMessage] = useState(""), [verificationBusy, setVerificationBusy] = useState(false);
  useEffect(() => { fetch("/api/team").then(async r => { if (!r.ok) throw new Error(); const data = await r.json(); const roster = (data.members || []) as Member[]; setMembers(roster); setMember(roster.find(x => x.id === memberId) || null); }).catch(() => setError("Unable to load this employee profile.")); }, [memberId]);
  const update = (key: keyof Member, value: string) => setMember(current => current ? { ...current, [key]: key === "monthlySalary" ? Number(value) : value } : current);
  const save = async () => { if (!member) return; setSaving(true); setError(""); try { const response = await fetch("/api/team", { method: "PUT", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ members: members.map(item => item.id === member.id ? member : item) }) }); if (!response.ok) throw new Error(); setEditing(false); } catch { setError("Unable to save changes. Please try again."); } finally { setSaving(false); } };
  const verifyEmail = async (action: "send" | "verify") => { if (!member) return; setVerificationBusy(true); setVerificationMessage(""); try { const response = await fetch(`/api/team/${member.id}/email-verification`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action, code: verificationCode }) }); const data = await response.json(); if (!response.ok) throw new Error(data.error); if (action === "send") setVerificationMessage("Verification code sent. Ask the employee for the six-digit code."); else { setMember({ ...member, emailVerifiedAt: new Date().toISOString(), employeeAccessEnabled: true }); setVerificationMessage("Email verified. Employee portal access is enabled."); } } catch (cause) { setVerificationMessage(cause instanceof Error ? cause.message : "Unable to verify email."); } finally { setVerificationBusy(false); } };
  if (error && !member) return <div className="rounded-xl bg-rose-50 p-5 text-rose-700">{error}</div>;
  if (!member) return <div className="flex min-h-[55vh] items-center justify-center"><Loader2 className="h-6 w-6 animate-spin text-emerald-700" /></div>;
  const field = (key: keyof Member, type = "text") => editing ? <input type={type} value={String(member[key] ?? "")} onChange={e => update(key, e.target.value)} className={input} /> : <p className="mt-1 font-semibold text-slate-800">{String(member[key] || "Not added")}</p>;
  const initials = member.name.split(" ").map(n => n[0]).join("").slice(0, 2).toUpperCase();
  const employment: [keyof Member, string, string][] = [["department", "Department", "text"], ["role", "Designation", "text"], ["employmentType", "Employment type", "text"], ["joiningDate", "Joining date", "date"], ["reportingManager", "Reporting manager", "text"], ["monthlySalary", "Monthly salary", "number"]];
  const bank: [keyof Member, string][] = [["bankAccountHolder", "Account holder"], ["bankName", "Bank name"], ["bankAccountNumber", "Account number"], ["bankIFSC", "IFSC code"], ["bankBranch", "Branch"], ["bankAccountType", "Account type"], ["upiId", "UPI ID"]];
  return <div className="employee-profile-page mx-auto max-w-6xl space-y-6">
    <Link href="/admin/team?tab=profiles" className="inline-flex items-center gap-1.5 text-xs font-bold text-emerald-700 hover:underline"><ArrowLeft className="h-3.5 w-3.5" /> Back to employee profiles</Link>
    <section className="employee-profile-hero rounded-3xl border border-slate-200 bg-white text-slate-900 shadow-sm"><div className="flex flex-col gap-6 p-6 sm:flex-row sm:items-center sm:p-8"><div className="flex h-24 w-24 shrink-0 items-center justify-center rounded-full bg-slate-900 text-3xl font-black text-white">{initials}</div><div className="min-w-0 flex-1"><p className="text-xs font-bold uppercase tracking-[0.16em] text-slate-400">Employee profile</p>{editing ? <><input value={member.name} onChange={e => update("name", e.target.value)} className="mt-1 w-full max-w-md rounded-lg border border-slate-300 bg-white px-3 py-1 text-2xl font-extrabold text-slate-900 outline-none" /><input value={member.role} onChange={e => update("role", e.target.value)} className="mt-2 w-full max-w-md rounded-lg border border-slate-300 bg-white px-3 py-1 text-sm text-slate-700 outline-none" /></> : <><h1 className="mt-1 text-3xl font-extrabold">{member.name}</h1><p className="mt-1 text-sm text-slate-500">{member.role} · {member.territory || "Sunlife Solar"}</p></>}<div className="mt-4 flex flex-wrap gap-2"><span className="rounded-full bg-slate-100 px-3 py-1 text-xs font-bold text-slate-700">{member.category}</span><span className="rounded-full bg-emerald-50 px-3 py-1 text-xs font-bold text-emerald-700">{member.status}</span><span className="rounded-full bg-slate-100 px-3 py-1 text-xs text-slate-500">ID: {member.id}</span></div></div>{editing ? <div className="flex gap-2"><button onClick={() => setEditing(false)} className="rounded-xl bg-slate-100 px-4 py-3 text-sm font-bold text-slate-700">Cancel</button><button onClick={() => void save()} disabled={saving} className="inline-flex items-center gap-2 rounded-xl bg-slate-900 px-5 py-3 text-sm font-bold text-white disabled:opacity-60"><Save className="h-4 w-4" />{saving ? "Saving…" : "Save changes"}</button></div> : <button onClick={() => setEditing(true)} className="inline-flex items-center gap-2 rounded-xl bg-slate-900 px-5 py-3 text-sm font-bold text-white"><Pencil className="h-4 w-4" /> Edit profile</button>}</div></section>
    {error && <p className="rounded-xl border border-rose-200 bg-rose-50 p-3 text-sm text-rose-700">{error}</p>}
    <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-center"><div><p className="text-xs font-bold uppercase tracking-wide text-slate-400">Employee portal access</p><h2 className="mt-1 text-base font-extrabold text-slate-900">Email verification</h2><p className="mt-1 text-sm text-slate-500">{member.emailVerifiedAt ? "Verified email — employee self-service access is enabled." : "Send a six-digit code to validate the employee email."}</p></div><span className={`rounded-full px-3 py-1.5 text-xs font-bold ${member.emailVerifiedAt ? "bg-emerald-50 text-emerald-700" : "bg-amber-50 text-amber-700"}`}>{member.emailVerifiedAt ? "Verified" : "Pending verification"}</span></div>{!member.emailVerifiedAt && <div className="mt-4 flex flex-col gap-2 sm:flex-row"><button disabled={!member.email || verificationBusy} onClick={() => void verifyEmail("send")} className="rounded-xl bg-slate-900 px-4 py-2.5 text-sm font-bold text-white disabled:opacity-50">{verificationBusy ? "Please wait…" : "Send verification code"}</button><input value={verificationCode} maxLength={6} onChange={event => setVerificationCode(event.target.value.replace(/\D/g, ""))} placeholder="Enter 6-digit code" className="rounded-xl border border-slate-200 px-3 py-2.5 text-sm outline-none focus:border-emerald-600" /><button disabled={verificationCode.length !== 6 || verificationBusy} onClick={() => void verifyEmail("verify")} className="rounded-xl bg-emerald-600 px-4 py-2.5 text-sm font-bold text-white disabled:opacity-50">Verify code</button></div>}{verificationMessage && <p className="mt-3 text-sm font-medium text-slate-600">{verificationMessage}</p>}</section>
    <div className="grid gap-6 lg:grid-cols-[0.9fr_1.6fr]"><aside className="space-y-6"><section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="text-sm font-extrabold text-slate-900">Contact Details</h2><dl className="mt-4 space-y-4"><div><dt className={label}>Mobile number</dt>{field("phone", "tel")}</div><div><dt className={label}>Email</dt>{field("email", "email")}</div><div><dt className={label}>Date of birth</dt>{field("dob", "date")}</div><div><dt className={label}>Address</dt>{field("address")}</div></dl></section><section className="rounded-2xl border border-emerald-100 bg-emerald-50/60 p-5"><h2 className="text-sm font-extrabold text-emerald-950">Skills & Expertise</h2><div className="mt-4 flex flex-wrap gap-2">{member.skills?.length ? member.skills.map(skill => <span key={skill} className="rounded-lg border border-emerald-200 bg-white px-2.5 py-1 text-xs font-semibold text-emerald-800">{skill}</span>) : <span className="text-sm text-slate-500">No skills added</span>}</div></section></aside><div className="space-y-6"><section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm sm:p-6"><h2 className="text-base font-extrabold text-slate-900">Employment Overview</h2><div className="mt-5 grid gap-4 sm:grid-cols-2">{employment.map(([key, title, type]) => <div key={String(key)} className="rounded-xl bg-slate-50 p-4"><p className={label}>{title}</p>{field(key, type)}</div>)}</div></section><section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm sm:p-6"><h2 className="text-base font-extrabold text-slate-900">Bank & Payment Details</h2><div className="mt-5 grid gap-4 sm:grid-cols-2">{bank.map(([key, title]) => <div key={String(key)}><p className={label}>{title}</p>{editing || key !== "bankAccountNumber" ? field(key) : <p className="mt-1 font-mono font-semibold text-slate-800">{member.bankAccountNumber ? `•••• ${member.bankAccountNumber.slice(-4)}` : "Not added"}</p>}</div>)}</div></section></div></div>
  </div>;
}
